import type { NextPage } from "next";
import Head from "next/head";
import Navigation from "../components/Navigation";
import Stopwatch from "../components/Stopwatch";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col min-h-screen justify-between items-center bg-purple-700">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <Navigation />

        <Stopwatch />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
